# Base configuration for Adaptive Learning Agent

# Learning Progress Drive Configuration
learning_progress:
  smoothing_window: 500
  derivative_clamp: [-1.0, 1.0]
  boredom_threshold: 0.01
  boredom_steps: 500
  lp_weight: 0.7
  empowerment_weight: 0.3
  use_adaptive_weights: false

# Memory System Configuration
memory:
  memory_size: 512
  word_size: 64
  num_read_heads: 4
  num_write_heads: 1
  controller_size: 256

# Energy System Configuration
energy:
  max_energy: 100.0
  base_consumption: 0.01
  action_multiplier: 0.5
  computation_multiplier: 0.001
  food_energy_value: 10.0

# Death and Memory Preservation
death_system:
  use_learned_importance: false
  preservation_ratio: 0.2

# Environment Configuration
environment:
  visual_size: [3, 64, 64]
  proprioception_size: 12
  action_space_size: 8
  max_episode_steps: 10000

# Training Configuration
training:
  batch_size: 32
  learning_rate: 0.001
  gradient_clip: 1.0
  device: "cuda"  # or "cpu"

# Monitoring Configuration
monitoring:
  log_interval: 100
  save_interval: 1000
  metrics_buffer_size: 10000
  enable_wandb: true
  project_name: "adaptive-learning-agent"

# Experiment Configuration
experiment:
  seed: 42
  num_runs: 5
  max_steps: 50000
  validation_interval: 5000