# Phase 0: Component Isolation and Validation

# Inherit from base config
defaults:
  - base_config

# Override for Phase 0 testing
learning_progress:
  smoothing_window: 100  # Smaller for faster testing
  boredom_steps: 50

memory:
  memory_size: 64  # Smaller for testing
  word_size: 16
  controller_size: 32

energy:
  max_energy: 50.0  # Smaller for faster death testing

environment:
  visual_size: [3, 32, 32]  # Smaller for faster processing
  proprioception_size: 4
  max_episode_steps: 1000

experiment:
  max_steps: 5000  # Shorter experiments for validation
  num_runs: 3

# Phase 0 specific settings
phase0:
  enable_bootstrap_protection: true
  protection_steps: 1000
  synthetic_data_length: 1000
  validation_tests:
    - breakthrough_detection
    - boredom_detection
    - noise_robustness
    - multi_modal_handling
    - outlier_robustness