# ARC-AGI-3 Training Configuration
# Modify these settings without changing code

# Training Mode Configuration
training_mode:
  swarm_enabled: false          # true = SWARM mode (concurrent), false = sequential
  max_concurrent_games: 3       # Only used if swarm_enabled = true
  
# Memory/Salience Configuration  
memory_mode:
  salience_mode: "decay_compression"  # Options: "lossless", "decay_compression", "adaptive_compression"
  enable_salience_comparison: false   # Compare multiple salience modes
  memory_consolidation_threshold: 0.8 # When to trigger memory consolidation

# Training Parameters
training_params:
  target_win_rate: 0.85         # 85% target win rate
  target_avg_score: 75.0        # Target average score
  max_episodes_per_game: 50     # Episodes per game (adaptive)
  max_training_iterations: 20   # Maximum training iterations
  game_count: 6                 # Number of games to train on
  difficulty_preference: "mixed" # "easy", "medium", "hard", "mixed"

# API Configuration
api_config:
  create_real_scorecard: true   # Create real scorecards on ARC-AGI-3
  verify_connection: true       # Verify API before training
  timeout_seconds: 30           # API timeout

# Sleep System Configuration
sleep_config:
  enable_sleep_cycles: true     # Enable sleep/wake cycles
  sleep_trigger_threshold: 0.3  # Energy level to trigger sleep
  memory_compression_during_sleep: true

# Adaptive Training Configuration
adaptive_config:
  adjust_episodes_based_on_performance: true
  increase_episodes_on_poor_performance: true
  switch_salience_mode_after_iterations: 3  # Switch from lossless to compression after N iterations
